spring:
    servlet:
        multipart:
            max-file-size: 20MB
            max-request-size: 20MB

server:
    port: 8085

eureka:
    instance:
        preferIpAddress: true
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/

s3.storage.url: http://localhost:4566

storage:
    service:
        url: http://localhost:8085/storages/type